# this is the K8S frontend deployment descriptor used for containerized builds
# it was created following console-dot's containerized-FE migration guide:
# https://consoledot.pages.redhat.com/docs/dev/containerized-frontends/migration/migration.html#_step_5_create_the_frontend_resource_yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json

apiVersion: v1
kind: Template
metadata:
  name: openshift
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: openshift
    spec:
      feoConfigEnabled: true
      envName: ${ENV_NAME}
      title: OCM UI
      deploymentRepo: https://github.com/RedHatInsights/uhc-portal
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/openshift
      image: ${IMAGE}:${IMAGE_TAG}
      bundleSegments:
        - segmentId: openshift
          bundleId: openshift
          position: 100
          navItems: 
            - id: overview
              title: Overview
              href: /openshift/overview
              product: Red Hat OpenShift Cluster Manager
            - id: cluster-management
              groupId: cluster-management
              title: Cluster Management
              navItems:
                - id: dashboard
                  title: Dashboard
                  href: /openshift/dashboard
                  product: Red Hat OpenShift Cluster Manager
                - id: clusters
                  title: Cluster List
                  href: /openshift/cluster-list
                  product: Red Hat OpenShift Cluster Manager
                # TODO: Replace advisor with navigationSegment from https://github.com/RedHatInsights/ocp-advisor-frontend/blob/master/deploy/frontend.yml
                - id: advisor
                  title: Advisor
                  expandable: true
                  routes:
                    - id: recommendations
                      title: Recommendations
                      href: /openshift/insights/advisor/recommendations
                      product: Red Hat OpenShift Cluster Manager
                    - id: advisor-clusters
                      title: Clusters
                      href: /openshift/insights/advisor/clusters
                      product: Red Hat OpenShift Cluster Manager
                    - id: workloads
                      title: Workloads
                      href: /openshift/insights/advisor/workloads
                      product: Red Hat OpenShift Cluster Manager
                      permissions:
                        - method: featureFlag
                          args: ["ocp-advisor-ui-workloads", true]
                        - method: featureFlag
                          args: ["ocp-advisor-workloads-release", true]
                # TODO: Replace vulnerability-dashboard with navigationSegment from https://github.com/RedHatInsights/vuln4shift-frontend/blob/master/deploy/frontend.yml
                - id: vulnerability-dashboard
                  title: Vulnerability Dashboard
                  expandable: true
                  routes:
                    - id: cves
                      title: CVEs
                      href: /openshift/insights/vulnerability/cves
                      product: Red Hat OpenShift Cluster Manager
                    - id: vulnerability-clusters
                      title: Clusters
                      href: /openshift/insights/vulnerability/clusters
                      product: Red Hat OpenShift Cluster Manager
                - id: subscriptions
                  title: Subscriptions
                  expandable: true
                  routes:
                    - id: subscriptions-usage
                      title: OpenShift Usage
                      href: /subscriptions/usage/openshift
                    - id: annual-subscriptions
                      title: Annual Subscriptions
                      href: /openshift/quota
                - segmentRef:
                    segmentId: cost-management
                    frontendName: cost-management
            - id: products
              groupId: products
              title: Products
              navItems:
                - id: acm
                  title: Advanced Cluster Management
                  href: https://catalog.redhat.com/software/container-stacks/detail/5ec54aa3535cb70ab8c02996
                  isExternal: true
                - segmentRef:
                    segmentId: acs
                    frontendName: acs
                # TODO: Replace openshift-ai with navigationSegment from https://github.com/RedHatInsights/developer-sandbox-ui/blob/master/deploy/frontend.yaml
                - id: openshift-ai
                  title: OpenShift AI
                  expandable: true
                  routes:
                    - id: developer-sandbox-trial
                      title: Developer Sandbox | OpenShift AI
                      href: https://sandbox.redhat.com
                      isExternal: true
                    - id: sixty-day-trial
                      title: 60-Day Product Trial | OpenShift AI
                      href: https://www.redhat.com/en/technologies/cloud-computing/openshift/openshift-ai/trial
                      isExternal: true
                - id: openshift-virtualization
                  title: OpenShift Virtualization
                  href: https://catalog.redhat.com/software/container-stacks/detail/5ec53f218b6f188e53644c4f
                  isExternal: true
                - id: operators
                  title: Operators
                  href: /openshift/overview#recommended-operators
            - id: resources
              groupId: resources
              title: Resources
              navItems:
                # TODO: Replace learning-resources with navigationSegment from https://github.com/RedHatInsights/learning-resources/blob/master/deploy/frontend.yml
                - id: learning-resources
                  title: Learning Resources
                  href: /openshift/learning-resources
                # TODO: Replace developer-sandbox with navigationSegment from https://github.com/RedHatInsights/developer-sandbox-ui/blob/master/deploy/frontend.yaml
                - id: developer-sandbox
                  title: Developer Sandbox
                  href: https://sandbox.redhat.com
                  isExternal: true
                - id: downloads
                  title: Downloads
                  href: /openshift/downloads
                  product: Red Hat OpenShift Cluster Manager
                - id: releases
                  title: Releases
                  href: /openshift/releases
      serviceTiles:
        - section: containers
          group: openshift
          id: overview
          href: /openshift/overview
          title: Overview
          description: Browse options for various OpenShift cluster types to find what fits your needs.
          icon: OpenShiftIcon
        - section: containers
          group: openshift
          id: clusters
          href: /openshift/cluster-list
          title: Clusters
          description: View, Register, or Create an OpenShift Cluster.
          icon: OpenShiftIcon
        - section: inventories
          group: openshift
          id: cluster-list
          href: /openshift/cluster-list
          title: Cluster List
          description: View, Register, or Create an OpenShift Cluster.
          icon: OpenShiftIcon
        - section: operators
          group: openshift
          id: openshift-ai
          href: https://catalog.redhat.com/software/container-stacks/detail/63b85b573112fe5a95ee9a3a
          title: OpenShift AI
          description: Run and manage virtual machines on OpenShift.
          icon: OpenShiftIcon
          isExternal: true
        - section: operators
          group: openshift
          id: openshift-virtualization
          href: https://catalog.redhat.com/software/container-stacks/detail/5ec53f218b6f188e53644c4f
          title: OpenShift Virtualization
          description: Run and manage virtual machines on OpenShift.
          icon: OpenShiftIcon
          isExternal: true
        - section: operators
          group: openshift
          id: acm
          href: https://catalog.redhat.com/software/container-stacks/detail/5ec54aa3535cb70ab8c02996
          title: Advanced Cluster Management for Kubernetes
          description: Manage cluster lifecycles, deploy workloads, and enforce policies across your Kubernetes fleet.
          icon: OpenShiftIcon
          isExternal: true
        - section: operators
          group: openshift
          id: gitops
          href: https://catalog.redhat.com/software/container-stacks/detail/5fb288c70a12d20cbecc6056
          title: OpenShift GitOps
          description: Build and integrate declarative, Git-driven CD workflows into your application platform.
          icon: OpenShiftIcon
          isExternal: true
        - section: operators
          group: openshift
          id: pipelines
          href: https://catalog.redhat.com/software/container-stacks/detail/5ec54a4628834587a6b85ca5
          title: Pipelines
          description: Design custom CI/CD pipelines to build, test, and deploy applications.
          icon: OpenShiftIcon
          isExternal: true
        - section: operators
          group: openshift
          id: service-mesh
          href: https://catalog.redhat.com/software/container-stacks/detail/5ec53e8c110f56bd24f2ddc4
          title: OpenShift Service Mesh
          description: Monitor and manage microservices with a unified service mesh.
          icon: OpenShiftIcon
          isExternal: true
        - section: tryBuy
          group: openshift
          id: rosa-hands-on-experience
          href: /openshift/services/rosa/demo/
          title: ROSA Hands-on Experience
          description: Access a production-ready ROSA cluster for a limited time in a demo environment.
          icon: OpenShiftIcon 
      searchEntries:
        - id: rosa
          title: Red Hat OpenShift Service for AWS
          href: /openshift/create/rosa/getstarted
          description: ROSA allows you to deploy fully operational and managed Red Hat OpenShift clusters while leveraging the full breadth and depth of AWS.
        - id: create-clusters-aws
          title: Red Hat OpenShift on AWS
          href: /openshift/create
          description: Create a Red Hat OpenShift cluster on AWS.
          alt_title:
            - AWS
            - ROSA
            - OpenShift on AWS
        - id: create-clusters-azure
          title: Red Hat OpenShift on Azure
          href: /openshift/create
          description: Create a Red Hat OpenShift cluster on Azure.
          alt_title:
            - ARO
            - Azure
            - OpenShift on Azure
        - id: create-clusters-dedicated
          title: Red Hat OpenShift Dedicated
          href: /openshift/create
          description: Create a Red Hat OpenShift cluster on dedicated hardware.
          alt_title:
            - OSD
            - Dedicated
            - GCP
            - AWS
            - OpenShift on AWS
            - OpenShift on GCP
        - id: create-clusters-ibm
          title: Red Hat OpenShift on IBM Cloud
          href: /openshift/create
          description: Create a Red Hat OpenShift cluster on IBM Cloud.
          alt_title:
            - ROKS
            - IBM Cloud
            - OpenShift on IBM Cloud
        - id: cluster-manager
          title: Cluster Manager
          href: /openshift
          description: View, Register, or Create an OpenShift Cluster.
      module:
        manifestLocation: "/apps/openshift/fed-mods.json"
        moduleConfig:
          ssoScopes:
            - rhfull
        modules:
          - id: "openshift"
            module: "./RootApp"
            routes:
              - pathname: /openshift
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/app-sre/uhc-portal
